version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    env_file:
      - ./services/user-service/.env
    networks:
      - ecommerce-network

  product-catalog-service:
    build:
      context: ./services/product-catalog-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    env_file:
      - ./services/product-catalog-service/.env
    networks:
      - ecommerce-network

  shopping-cart-service:
    build:
      context: ./services/shopping-cart-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    env_file:
      - ./services/shopping-cart-service/.env
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    env_file:
      - ./services/order-service/.env
    networks:
      - ecommerce-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
    env_file:
      - ./services/payment-service/.env
    networks:
      - ecommerce-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
    env_file:
      - ./services/notification-service/.env
    networks:
      - ecommerce-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      - product-catalog-service
      - shopping-cart-service
      - order-service
      - payment-service
      - notification-service
networks:
  ecommerce-network:
    driver: bridge
    